### ISSUE TITLE
Use full RDFa Entailment if vocab_expansion option given

### ISSUE THREAD

**Issue by gkellogg** [w3c/microdata-rdf#11]
The current spec duplicates rules for vocabulary entailment from RDFa, but also allows RDFa entailment. Issue #10 suggests making vocabulary expansion (and entailment) controlled by a processor option. Also, since original publication, schema.org is now publishing an RDFs vocabulary at http://schema.org/docs/schema_org_rdfa.html. If this vocabulary contained the following statement:

```
schema:additionalType rdfs:subPropertyOf rdf:type .
```

the need for special registry rules for `additionalType` would be removed, provided that RDFa vocabulary expansion is performed, where the schema.org vocabulary is used to perform entailment operations.

**Comment by iherman** [comment]
I would propose not to do this. RDFa entailment is a tiny bit more complex that what microdata requires, and we should go for the maximum simplicity, in view of the audience. Let us stick to the minimum that makes sense for microdata, i.e., with what is in the document.

If you agree, I think we can close this issue

**Comment by gkellogg** [comment]
This is obsoleted due to simplified vocabulary expansion now included in issue #10.
