### ISSUE TITLE
Test 0001 does not match description in manifest

### ISSUE THREAD

**Issue by sesuncedu** [w3c/microdata-rdf#14]
Manifest says

```
      rdfs:comment "Item with no itemtype and literal itemprop";
      mf:action <0001.html>;
```

But the action file contains: 

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Test 001</title>
  </head>
  <body>
    <p itemscope itemtype="http://schema.org/Person">This test created by <span itemprop="name">Gregg Kellogg</span>.</p>
  </body>
</html>
```

Which matches the expected result:

```
@prefix schema: <http://schema.org/> .
[ a schema:Person; schema:name "Gregg Kellogg"] .
```

**Comment by sesuncedu** [comment]
Writing a custom JUnit Test Runner, which includes the comment in the display name, so I had to check this.

**Comment by gkellogg** [comment]
Indeed, a poor name. Probably due to a transcoding error when transferred from my original RSpecs. Feel free to submit pull-requests for such issues, and if you'd like to suggest more tests.

**Comment by sesuncedu** [comment]
Gregg Kellogg's a perfectly good name :-) 

Not sure which way the error is going: it's either a right test with the wrong description, or a right description with the wrong test (test 2 and 3 have no itemtype).
