### ISSUE TITLE
Add preferred prefixName to registry? 

### ISSUE THREAD

**Issue by sesuncedu** [w3c/microdata-rdf#17]
This would be useful for prefix aware output forms. Have to parse the IRI anyway, so might as well take advantage of it.

**Comment by gkellogg** [comment]
No other serialization format keeps prefixes when parsing, as prefixes are not an RDF concept, but that of a serialization. As microdata has no such concept, I'm not sure that this makes any sense. Prefix information is available in other places, such as the RDFa Initial Context, but I don't see the value in adding that to the registry.

**Comment by iherman** [comment]
I agree. The conversion aims at an abstract RDF graph, not a particular serialization.

Ivan

> On 15 Dec 2014, at 01:47 , Gregg Kellogg notifications@github.com wrote:
> 
> No other serialization format keeps prefixes when parsing, as prefixes are not an RDF concept, but that of a serialization. As microdata has no such concept, I'm not sure that this makes any sense. Prefix information is available in other places, such as the RDFa Initial Context, but I don't see the value in adding that to the registry.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by sesuncedu** [comment]
Section 5 on Web processors is where the concrete spec is used.

**Comment by iherman** [comment]
I have the impression that there is a confusion with the terminology. The document uses the term `URI prefix` (see http://www.w3.org/TR/2014/NOTE-microdata-rdf-20141216/#dfn-uri-prefix) but that is _not_ the prefix in the sense of a CURIE or Turtle. I guess there is a conflation with the terminology used in the microdata spec, but we have to live with this I am afraid.

I mark this issue as closed for now.
