### ISSUE TITLE
Why is registry for an RDF related specification defined in JSON? 

### ISSUE THREAD

**Issue by sesuncedu** [w3c/microdata-rdf#18]
Why is the registry NOT defined in OWL and encoded in RDF?

**Comment by gkellogg** [comment]
This was considered when the original note was created, but the available JSON encodings, at the time, weren't useful for this. At this point, it could be done in JSON-LD, but would also affect processor implementations to no great advantage. Adding a separate registry definition parallel to md.json which was RDF could be useful, although it would need a corresponding vocabulary.

**Comment by iherman** [comment]
What problem would that solve?

Ivan

> On 14 Dec 2014, at 16:51 , Simon Spero notifications@github.com wrote:
> 
> Why is the registry NOT defined in OWL and encoded in RDF?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
I guess this boat has sailed anyway. Changing the registry syntax now would mean really disagreeable compatibility issues with existing processors, for not much value.

Besides, the registry does not define any vocabulary of real importance, so OWL would be an overkill.

I close the issue now.
