### ISSUE TITLE
Why is the mandatory output format n-triples 1.1? 

### ISSUE THREAD

**Issue by sesuncedu** [w3c/microdata-rdf#19]
All examples and test cases use more  turtle.

**Comment by gkellogg** [comment]
All RDF processors state their output expectations using N-Triples, which is specifically what the format was designed for. (RDFa uses SPARQL for various reasons). The job a a processor is to render markup into an RDF graph. The result is just a neutral representation of the expected graph. My own test running operates by parsing the microdata to a graph and parsing the results (N-Triples) to a graph and then comparing them for isomorphism. At that point, it wouldn't matter what form the results were specified in, but this removes a dependency on some other processor format.

**Comment by iherman** [comment]
I know of at least one RDF implementation that does _not_ have a Turtle serialization ([rdf store for javascript](https://github.com/antoniogarrote/rdfstore-js), whereas all of them (including rdf store) have an N-Triples output. N-Triples is the lowest common denominator, i.e., the tests should really stay in that format in my view.

**Comment by sesuncedu** [comment]
The tests are all in turtle.  This confused me briefly for all the wrong
reasons (what's the deal with all these relative IRIs?

The square brackets and @prefix didn't register.

If the test-output does go to n-triples, it would be handy if the html test
cases gained embedded base elements (at the moment, everything that would
be in a  w3c.github.io IRI if the base were applied is totally relative, so
there's no need to set a custom base IRI when running against a checked out
copy  ).

BTW,  http://www.w3.org/ns/md and http://www.w3.org/ns/md.json don't seem
to have gotten pushed; is that part of the server managed by someone else?

```
Last-Modified: Sat, 01 Dec 2012 22:45:21 GMT
ETag: "6ab-4cfd245626240"
```

**Comment by gkellogg** [comment]
The [test manifest](http://w3c.github.io/microdata-rdf/tests/) says the following:

> Tests are described with individual HTML files containing microdata, which when processed, generates exactly the triples specified in the result file.

Both the `input` and `result` files generate triples, they should generate the same triples. It's not that the output formats are expected to be the same. Perhaps it would be more clear with wording from [RDF 1.1 Test Cases](http://www.w3.org/TR/rdf11-testcases/):

> A positive test is passed if an implementation parses the input (identified by the object of the mf:action property) using the appropriate syntax into a graph or dataset, parses the expected result (identified by the object of the mf:result property) into another graph or dataset, and those two graphs/datasets are isomorphic (see [RDF11-CONCEPTS]).

Although, there is a sentence that says `These tests generally correspond to the descriptions of Evaluation Tests in [RDF11-TESTCASES]`.

Taking both to abstract RDF graphs also helps deal with serialization differences in encoding simple literals.

Also, as indicated in the test manifest:

> All tests should be performed with an assumed base of http://w3c.github.io/microdata-rdf/tests/ along with the base-name of the specific test document (excluding any format extension).

This deals with the relative-URI issues.

@iherman had a reminder to push the registry files, presumably he'll take care of that in short order.

**Comment by sesuncedu** [comment]
To be clear: the output format in question is the one specified as the base
requirement for a web service; I'm doing all comparison as graph
isomorphism ; I am also being lazy and using the physical URL as the base
rather than feeding in the default, which happens to work for these files.

**Comment by gkellogg** [comment]
Okay, I'm not sure if we've addressed your concerns. Other than the registry, are there open issues with the manifest? If not, perhaps you can close this issue. If so, what do you think needs to change to satisfy your issues?
