### ISSUE TITLE
Format IRI for Microdata?

### ISSUE THREAD

**Issue by sesuncedu** [w3c/microdata-rdf#21]
Should there be a format IRI defined for Microdata under http://www.w3.org/ns/formats/ ?

``` xml
<http://www.w3.org/ns/formats/md>
```

might work?

**Comment by gkellogg** [comment]
Yeah, there probably should be. @iherman should be able to handle this.

**Comment by iherman** [comment]
Done: http://www.w3.org/ns/formats/microdata

Ivan

> On 23 Dec 2014, at 03:04 , Gregg Kellogg notifications@github.com wrote:
> 
> Yeah, there probably should be. @iherman should be able to handle this.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Thanks, Ivan!
