### ISSUE TITLE
HTTP to HTTPS breaks Test 0026

### ISSUE THREAD

**Issue by HansBrende** [w3c/microdata-rdf#30]
@gkellogg `Test 0026: Web Schemas TF: Schema.org tests: test 11` in the test results has an expected object url of `http://w3c.github.io/author/jd_salinger.html` however the url is specified as the relative url `/author/jd_salinger.html` in the actual microdata, so my parser resolves it as `https://w3c.github.io/author/jd_salinger.html`, since that page is on HTTPS.

**Comment by gkellogg** [comment]
I'll put it on my queue. Obviously, things have changed since the test suite was originally created.

**Comment by gkellogg** [comment]
@HansBrende if you note the instructions on the [test page](https://w3c.github.io/microdata-rdf/tests/) it says to run the tests with an assumed base of `http://w3c.github.io/microdata-rdf/tests/`, so probably best to use that in your test runner. If retrieving from the web, you can override the file location of the returned result. Many instrument their test runners to run from a local copy.

At this point, I'm reluctant to change the test suite based on change from http to https, given the specific information in place for how to run the test suite.

**Comment by HansBrende** [comment]
@gkellogg I must have missed that when reading through the instructions. Thanks for the info!
