### ISSUE TITLE
Implementation reports?

### ISSUE THREAD

**Issue by rubensworks** [w3c/microdata-rdf#31]
I understand this spec is not recommended (yet?), but I was wondering if there's a place to share EARL implementation reports, as I recently finalized [an implementation](https://github.com/rubensworks/microdata-rdf-streaming-parser.js) of this algorithm.

**Comment by gkellogg** [comment]
Certainly, doing an implementation report would be fairly straightforward, but I think @iherman and I discussed this and rejected the notion, potentially leaving it for some future group, which is unlikely to ever happen.

At W3C Implementation reports are traditionally used for the transition from PR, which can't happen for a note, but clearly [there's precedent](https://w3c.github.io/json-ld-streaming/reports/) for a note (at least a WG Note) to have an implementation report.

Going back and touching the Note to re-publish with an implementation report link, as well as needing a call for implementations is probably too late now. Of course, you could consider using the [earl-report](https://rubygems.org/gems/earl-report) tool with a template and publish it on your own repository. I do this for [rdf-tabular](https://htmlpreview.github.io/?https://github.com/ruby-rdf/rdf-tabular/blob/develop/etc/earl.html), using the template and instructions found [here](https://github.com/ruby-rdf/rdf-tabular/tree/develop/etc).

**Comment by rubensworks** [comment]
Thanks for the clarification! I may indeed look into publishing a report in my own repo as you suggested.
