### ISSUE TITLE
Remove top-level md:item list

### ISSUE THREAD

**Issue by gkellogg** [w3c/microdata-rdf#6]
As a holdover from the original Microdata version of the RDF transformation, all top-level items are added to a list. This was included to maintain the ordered top-level items from the original spec, but has little use in an RDF case, and just adds clutter.

**Comment by iherman** [comment]
I fully agree it is useless:-)

**Comment by iherman** [comment]
On second thought... I think the RDF->Microdata should follow whatever the microdata spec says. So I am actually wondering whether we should remove it or not... The ideal would be to remove the reference to order from the microdata spec itself. So, again on second thought, I am more in favor of keeping it as is...

**Comment by gkellogg** [comment]
It his came from the original Hixie version of the transform, as every tipping was ordered to mirror the way the JSON is created. We dropped this for property values, removing it for top-level item ordering is consistent with that, and doesn't violate any core requirement of the Microdata note. It's also entirely useless for the schema.org use case, which is really the only one that matters, IMO.

**Comment by iherman** [comment]
On 01 Nov 2014, at 08:20 , Gregg Kellogg notifications@github.com wrote:

> It his came from the original Hixie version of the transform, as every tipping was ordered to mirror the way the JSON is created. We dropped this for property values, removing it for top-level item ordering is consistent with that, and doesn't violate any core requirement of the Microdata note. It's also entirely useless for the schema.org use case, which is really the only one that matters, IMO.

That it is useless: I fully agree.

But I think you are right: I scanned (quickly) through the microdata document and the order seems to be artifact of JSON, in fact, ie, that there is no other way to have a collection of things than putting them into an array. (The same issue JSON-LD has when there are several 'top-level' subjects.) This is not meaningful for RDF. Ie, I am fine dropping this.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by iherman** [comment]
I am happy closing this issue by dropping that triple and the list
