### ISSUE TITLE
Extract literal from @content of meta element

### ISSUE THREAD

**Issue by gkellogg** [w3c/microdata-rdf#7]
For some reason, this was left out of the published note. The HTML `meta` element is used specifically to provide metadata using the value of the `@content` attribute [[1]](http://www.w3.org/TR/html/document-metadata.html#the-meta-element).

```
<meta itemprop="meta" content="foo"/>
```

would generate the following:

```
[ <http://schema.org/meta> "foo" ] .
```

**Comment by iherman** [comment]
+1

Ivan

> On 02 Nov 2014, at 18:50 , Gregg Kellogg notifications@github.com wrote:
> 
> For some reason, this was left out of the published note. The HTML meta element is used specifically to provide metadata using the value of the @content attribute [1].
> 
> <meta itemprop="meta" content="foo"/>
> 
> would generate the following:
> 
> [ http://schema.org/meta "foo" ] .
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me
