### ISSUE TITLE
Extract literal from @value of meter element

### ISSUE THREAD

**Issue by gkellogg** [w3c/microdata-rdf#9]
The `meter` element represents a scalar measurement within a known range, or a fractional value; for example disk usage, the relevance of a query result, or the fraction of a voting population to have selected a particular candidate.

Depending on the lexical form of the value of the `@value` attribute:
1. if the value has the lexical form of an `xsd:integer`, value is a literal with datatype `xsd:integer`
2. if the value has the lexical form of an `xsd:float`, value is a literal with datatype `xsd:float`
3. if the value has the lexical form of an `xsd:double`, value is a literal with datatype `xsd:double`
4. Otherwise, value is a Plain Literal without language or datatype.

The follow markup:

```
<meter itemprop="integer" value="1">1cm</meter>
<meter itemprop="float" value="1.1">1.1cm</meter>
<meter itemprop="double" value="1.1e1">1.1<sup>1</sup></meter>
<meter itemprop="plain" value="foo">foo</meter>
```

would generate the following:

```
[
  <http://example/integer > "1"^^xsd:integer;
  <http://example/float> "1.1"^^xsd:float;
  <http://example/double> "1.1e1"^^xsd:double;
  <http://example/plain> "foo";
] .
```

**Comment by iherman** [comment]
The only caveat is that differentiating between double and float is not that simple if the underlying infrastructure does not have explicit conversions for it. Eg, python, out of the box, does not make any difference (in fact, everything is a double). So maybe we can require to generate double everywhere to avoid this problem...

Ivan

> On 02 Nov 2014, at 21:57 , Gregg Kellogg notifications@github.com wrote:
> 
> The HTMLmeter element is used specifically to provide metadata using the value of the @value attribute [1]. As this attribute is intended to be machine-readable, a datatyped value may result.
> 
> Depending on the lexical form of the value of the @value attribute:
> 
>   • if the value has the lexical form of an xsd:integer, value is a literal with datatype xsd:integer
>   • if the value has the lexical form of an xsd:float, value is a literal with datatype xsd:float
>   • if the value has the lexical form of an xsd:double, value is a literal with datatype xsd:double
>   • Otherwise, value is a Plain Literal without language or datatype.
> The follow markup:
> 
> <meter itemprop="integer" value="1">1cm</meter>
> <meter itemprop="float" value="1.1">1.1cm</meter>
> <meter itemprop="double" value="1.1e1">1.1<sup>1</sup></meter>
> <meter itemprop="plain" value="foo">foo</meter>
> 
> would generate the following:
> 
> [
>   <http://example/integer > "1"^^xsd:integer;
>   http://example/float "1.1"^^xsd:float;
>   http://example/double "1.1e1"^^xsd:double;
>   http://example/plain "foo";
> ] .
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by gkellogg** [comment]
So, using the DOM, you don't have access to the lexical form in Python? Otherwise, I don't see the problem.

That said, I could live without supporting xsd:double.

**Comment by iherman** [comment]
> On 03 Nov 2014, at 16:14 , Gregg Kellogg notifications@github.com wrote:
> 
> So, using the DOM, you don't have access to the lexical form in Python? Otherwise, I don't see the problem.

Well... That means the implementation has to get into the parsing of the lexical form, instead of simply using the core library of the underlying environment. Ie

try :
    a = float("lexicalform")
except :
    # it is not a float/double, do something

I have to get and parse "lexicalform". Of course doable, but I am lazy:-) and I do not see the huge benefit...

Ivan

> That said, I could live without supporting xsd:double.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
The implementation, in languages that do not make a difference between float and double (e.g., Python) means that the value must be checked, e.g., whether it is larger than 3.40282366920938E38 to decide whether it is `xsd:double` or `xsd:float`. This can of course be done.

I am not sure it makes a huge difference in practice in the sense of whether it makes sense to differentiate between double and float. My instinct would say to use double and integer, and that is all, but I am happy to go with the flow. Apart from this detail, I am happy to move on with this as described.

**Comment by gkellogg** [comment]
The language in the spec supports just integer and float, is that sufficient? I a free that for most Microdata use, double isn't important.

**Comment by gkellogg** [comment]
Alternatively, I'd be fine with saying that if the form is float or double, use double.

**Comment by iherman** [comment]
> On 11 Nov 2014, at 16:42 , Gregg Kellogg notifications@github.com wrote:
> 
> Alternatively, I'd be fine with saying that if the form is float or double, use double.

That would certainly facilitate things. I do not think the world would collapse if we used only double.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
